version: "3.7"

services:
  db:
    image: postgres:16
    environment:
        POSTGRES_DB: helpdesk_dev
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - ./containers_data/db/postgres/data:/var/lib/postgresql/data
    ports:
     - "5442:5432"